### ISSUE TITLE
Email Body

### ISSUE THREAD

**Issue by Prathamesh1197** [Infosys/Intelligent-Bot-Management-#10]
Hi team after monitoring a anomaly in bot in the notification mail it say "Reason for Anomaly Detection: The Bot Status Value Terminated (status) is equal to the threshold value Completed (status)." However it should had been not equal to. Can someone please rectify this. PFBI for reference.
<img width="855" alt="Screenshot 2023-02-22 111942" src="https://user-images.githubusercontent.com/121120224/220534844-1a05cf01-1e10-4ead-aaf8-1899daa57702.png">

**Comment by SudhaAmsoleInfy** [comment]
Hi Prathamesh,

The email templates are part of the release package as well as source code. please check the flow the template is targeted and update the same.

relative path -  ~\processloader\Templates\Email

Regards,
Sudha Amsole
