### ISSUE TITLE
Windows Server for Super Bot

### ISSUE THREAD

**Issue by Prathamesh1197** [Infosys/Intelligent-Bot-Management-#3]
For Infosys Super bot as Pre-requisites it needs Windows Server 2012 R2 – 64 Bit. However, it seems that Windows Server 2012 R2 – 64 Bit is coming to an end. Hence the team as told to upgrade the server to latest or 2019 OS. Can anyone please confirm if Super Bot will work on latest and upgraded version's as well.

**Comment by SudhaAmsoleInfy** [comment]
Hi Prathamesh,

the OS version mentioned in the pre-requisites is the one which is minimum requirement and tested for that OS. 
unless we test it on any OS we can not comment on the compatibility.

Request you to update the community if your team has setup on the newer version of the OS and the compatibility status.

**Note -although intelligent bot management is not dependent on OS specific component except that OS has to be server based OS** 

Regards,
Sudha

**Comment by Prathamesh1197** [comment]
We have installed 2019 windows server and 2022 Sql express edition. Even in this version the super bot is working in our  internal environment.
