### ISSUE TITLE
Super Bot Console App

### ISSUE THREAD

**Issue by Prathamesh1197** [Infosys/Intelligent-Bot-Management-#5]
We were getting error while monitoring a blue prism bot using console app. Seems MSMQ messgae was not getting sent.
On analyzing found that one of the properties that is send message was not selected. In installation document there was confusion where the document says to check Send Message, Delete Message and Delete. However the screenshot shows Delete, Receive Message, Peek Message. For now we selected all Delete, Receive Message, Peek message and send message option using which we were able to run the console app.
Can the team please update the Intelligent bot document with exact info and screenshot on this so that helps going order to avoid this issue.

**Comment by SudhaAmsoleInfy** [comment]
although the snapshot is showing delete, receive & peek message options, please follow the instructions clearly mentioned to select **send and delete Option**
