### ISSUE TITLE
Service Monitoring Not Reflecting in RPA Control Centre

### ISSUE THREAD

**Issue by Prathamesh1197** [Infosys/Intelligent-Bot-Management-#7]
After monitoring a Windows service, the data is not getting reflected in RPA Control Centre.

**Comment by SudhaAmsoleInfy** [comment]
we have updated the Script execution dll in the Script Control Center services updated release which should resolve the issue. Please setup with new Script Control Center services, check and confirm.

**Comment by Prathamesh1197** [comment]
After using the special id which was added under administrators the superbot was able to reflect data in RPA control centre.
