### ISSUE TITLE
Windows Service is not remediating after monitoring anomaly

### ISSUE THREAD

**Issue by Prathamesh1197** [Infosys/Intelligent-Bot-Management-#9]
After running the console app and detecting the anomaly the remediation of starting the service is not occurring.

**Comment by SudhaAmsoleInfy** [comment]
Hi Prathamesh,

the issue was with the service account you were using which should have admin privilege on which the script will be downloaded and executed and should be LDAP/AD authenticated.

Regards,
Sudha
